const agents = [
  {
    id: 1,
    name: "Main Coordinator",
    role: "Central Hub",
    status: "idle",
    currentTask: "Awaiting next request from Jason",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 2,
    name: "Planner",
    role: "Strategy & Planning",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 3,
    name: "Marketing & Outreach",
    role: "Growth",
    status: "idle",
    currentTask: "Paused — awaiting new task from Jason",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 1,
    memory: [
      "Status: UNVERIFIED — previous claims of campaigns, posts, and A/B tests had no evidence",
      "Only verified output: 1 social post draft (2026-03-21)",
      "See: /documents/marketing/logs/marketing_execution_log.md",
    ],
    history: [
      { action: "Social post draft created (verified)", time: "2026-03-21", type: "success" },
      { action: "Facebook campaign — UNVERIFIED (no evidence)", time: "claimed", type: "error" },
      { action: "15 social posts — UNVERIFIED (14 missing)", time: "claimed", type: "error" },
      { action: "A/B test — UNVERIFIED (no evidence)", time: "claimed", type: "error" },
    ],
  },
  {
    id: 4,
    name: "Finance & Compliance",
    role: "Operations",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 5,
    name: "Data Analytics",
    role: "Intelligence",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 6,
    name: "Memory/Research",
    role: "Knowledge Base",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 7,
    name: "QA Review",
    role: "Quality Assurance",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 8,
    name: "Execution/Compiler",
    role: "Build & Deploy",
    status: "idle",
    currentTask: "Awaiting next task",
    workload: 0,
    tasksCompleted: 6,
    uptime: "Uptime unavailable",
    evidenceCount: 6,
    memory: [
      "Grimmond Proposal v1 — completed (verified)",
      "Grimmond Proposal v2 — completed (verified)",
      "Program 1 Mastermind — completed (verified)",
      "Program 2 From Tradie to Business Owner — completed (verified)",
      "Cover Page Test — completed (verified)",
      "Task Centre cleanup — completed (verified)",
    ],
    history: [
      { action: "GRIMMOND_PROPOSAL_BRANDED.pdf created", time: "2026-03-23 04:49", type: "success" },
      { action: "GRIMMOND_PROPOSAL_BRANDED_v2.pdf created", time: "2026-03-23 09:52", type: "success" },
      { action: "PROGRAM1 branded PDF created", time: "2026-03-23 16:32", type: "success" },
      { action: "PROGRAM2 branded PDF created", time: "2026-03-23 16:49", type: "success" },
      { action: "Cover page test PDF created", time: "2026-03-23 17:18", type: "success" },
      { action: "Task Centre pruned (9 stale tasks removed)", time: "2026-03-23 05:00", type: "success" },
    ],
  },
  {
    id: 9,
    name: "Next Agent",
    role: "Onboarding & Activation",
    status: "idle",
    currentTask: "No active task",
    workload: 0,
    tasksCompleted: 0,
    uptime: "Uptime unavailable",
    evidenceCount: 0,
    memory: [
      "No verified memory entries — evidence required",
    ],
    history: [],
  },
  {
    id: 10,
    name: "Manus Doc Creator",
    role: "Document Engine",
    status: "idle",
    currentTask: "Awaiting next document task",
    workload: 0,
    tasksCompleted: 3,
    uptime: "Uptime unavailable",
    evidenceCount: 3,
    memory: [
      "Primary document engine for all Supercharged Tradies proposals",
      "Brand: #2F8FE6 blue, black headings, white background, clean modern",
      "Engine: /skills/manus-doc-creator/scripts/manus_generate.py",
    ],
    history: [
      { action: "PROGRAM1 branded PDF via Manus", time: "2026-03-23 16:32", type: "success" },
      { action: "PROGRAM2 branded PDF via Manus", time: "2026-03-23 16:49", type: "success" },
      { action: "Cover page test via Manus", time: "2026-03-23 17:18", type: "success" },
    ],
  },
];
